apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: dynamic-port-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamic-port-server
    spec:
      hostNetwork: true
      containers:
        - name: dynamic-port-server
          image: gcr.io/hightowerlabs/dynamic-port-server:0.0.1
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "-register-instance-external-ip=true"
            - "-service-instance-name=$(POD_NAME)"
            - "-service-registry=104.196.242.40"

