apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: service-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: gcr.io/hightowerlabs/service-registry:0.0.2
          imagePullPolicy: Always
          args:
            - "-listen-addr=0.0.0.0:80"
          volumeMounts:
            - name: certs
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: certs
          hostPath:
            path: "/etc/ssl/certs"
