apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: service-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: gcr.io/hightowerlabs/service-registry:0.0.2
          imagePullPolicy: Always
          args:
            - "-api=0.0.0.0:10080"
            - "-http=0.0.0.0:80"
          ports:
            - name: api
              containerPort: 10080
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 300m
              memory: 20Mi
            requests:
              cpu: 200m
              memory: 10Mi
          volumeMounts:
            - name: certs
              mountPath: "/etc/ssl/certs"
      volumes:
        - name: certs
          hostPath:
            path: "/etc/ssl/certs"
