apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: register
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: register
    spec:
      hostNetwork: true
      containers:
        - name: server
          image: gcr.io/hightowerlabs/register:0.0.1
