apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      hostNetwork: true
      containers:
        - name: server
          image: gcr.io/hightowerlabs/server:0.0.1
          imagePullPolicy: Always
          env:
            - name: REGISTER_ADDR
              value: "104.196.244.199"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
